### ISSUE TITLE
Config does not quote CSS file assignment

### ISSUE THREAD

**Issue by Jefficus** [fdev31/bugrest#1]
br crashed on all attempted commands because the default CSS assignment in config file wasn't quoted. After correcting that, things seem to work. Now I can get on with my test drive. :-)

**Comment by fdev31** [comment]
Sorry for the delay, I really didn't see this issue (wasn't checking on this repo).
Which version are you using ?

**Comment by Jefficus** [comment]
I don't recall. I ended up going with a different tool.

**Comment by fdev31** [comment]
I'll close this bug then, but for my curiosity feel free to share the tool you selected!
(I tested many and made `br` because of my unsatisfaction with other tools...)
